server:
  port: 8001
spring:
  application:
    name: dclass-account
  cloud:
    nacos:
      discovery:

# 配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
